Ok, this CloudFormation SageMaker Notebook template validates...

diff --git a/cloudformation/SageMaker_Notebook.template.yaml b/cloudformation/SageMaker_Notebook.template.yaml
--- a/cloudformation/SageMaker_Notebook.template.yaml
+++ b/cloudformation/SageMaker_Notebook.template.yaml
@@ -49,7 +49,43 @@ Resources:
       NotebookInstanceLifecycleConfigName: stopidle
       OnStart:
         - Content:
-            Fn::Base64: ! NotebookStartScript
+            Fn::Base64: |
+              #!/bin/bash
+
+              set -e
+
+              # OVERVIEW
+              # This part of the script stops a SageMaker notebook once it's idle for more than 1 hour (default time)
+              # You can change the idle time for stop using the environment variable below.
+              # If you want the notebook the stop only if no browsers are open, remove the --ignore-connections flag
+              #
+              # Note that this script will fail if either condition is not met
+              #   1. Ensure the Notebook Instance has internet connectivity to fetch the example config
+              #   2. Ensure the Notebook Instance execution role permissions to SageMaker:StopNotebookInstance to stop the notebook 
+              #       and SageMaker:DescribeNotebookInstance to describe the notebook.
+              #
+
+              # PARAMETERS
+              IDLE_TIME=3600
+
+              echo "Fetching the autostop script"
+              wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py
+
+              echo "Starting the SageMaker autostop script in cron"
+
+              (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -
+
+              # OVERVIEW
+              # This part of the script sets username and email address in Git config
+
+              # PARAMETERS
+              YOUR_USER_NAME="rjurney"
+              YOUR_EMAIL_ADDRESS="russell.jurney@gmail.com"
+
+              sudo -u ec2-user -i <<EOF
+
+              git config --global user.name "$YOUR_USER_NAME"
+              git config --global user.email "$YOUR_EMAIL_ADDRESS"
 
   ExecutionRole:
     Type: "AWS::IAM::Role"
@@ -89,8 +125,6 @@ Resources:
   SageMakerNotebook:
     Type: AWS::SageMaker::NotebookInstance
     Properties:
-      # AdditionalCodeRepositories:
-      # - https://github.com/rjurney/netography.git
       DefaultCodeRepository: !GetAtt DefaultRepository.CodeRepositoryName
       DirectInternetAccess: Enabled
       InstanceType: ml.g4dn.2xlarge
@@ -98,3 +132,4 @@ Resources:
       RoleArn: !GetAtt ExecutionRole.Arn
       VolumeSizeInGB: 32
       LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
+      RootAccess: Enabled
