SageMaker notebook gets 'netographhy' conda environment installed as an ipykernel along with poetry

diff --git a/cloudformation/SageMaker_Notebook.template.yaml b/cloudformation/SageMaker_Notebook.template.yaml
--- a/cloudformation/SageMaker_Notebook.template.yaml
+++ b/cloudformation/SageMaker_Notebook.template.yaml
@@ -48,50 +48,61 @@ Resources:
     Properties:
       NotebookInstanceLifecycleConfigName: stopidle
       OnStart:
-        - Content:
-            Fn::Base64: |
-              #!/bin/bash
+        - Content: !Base64 |
+            #!/bin/bash
 
-              set -e
+            set -e
 
-              # OVERVIEW
-              # This part of the script stops a SageMaker notebook once it's idle for more than 1 hour (default time)
-              # You can change the idle time for stop using the environment variable below.
-              # If you want the notebook the stop only if no browsers are open, remove the --ignore-connections flag
-              #
-              # Note that this script will fail if either condition is not met
-              #   1. Ensure the Notebook Instance has internet connectivity to fetch the example config
-              #   2. Ensure the Notebook Instance execution role permissions to SageMaker:StopNotebookInstance to stop the notebook
-              #       and SageMaker:DescribeNotebookInstance to describe the notebook.
-              #
+            # OVERVIEW
+            # This part of the script stops a SageMaker notebook once it's idle for more than 1 hour (default time)
+            # You can change the idle time for stop using the environment variable below.
+            # If you want the notebook the stop only if no browsers are open, remove the --ignore-connections flag
+            #
+            # Note that this script will fail if either condition is not met
+            #   1. Ensure the Notebook Instance has internet connectivity to fetch the example config
+            #   2. Ensure the Notebook Instance execution role permissions to SageMaker:StopNotebookInstance to stop the notebook
+            #       and SageMaker:DescribeNotebookInstance to describe the notebook.
+            #
 
-              # PARAMETERS
-              IDLE_TIME=3600
+            # PARAMETERS
+            IDLE_TIME=3600
 
-              echo "Fetching the autostop script"
-              wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py
+            echo "Fetching the autostop script"
+            wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py
 
-              echo "Starting the SageMaker autostop script in cron"
+            echo "Starting the SageMaker autostop script in cron"
 
-              (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -
+            (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -
 
-              # OVERVIEW
-              # This part of the script sets username and email address in Git config
+            # OVERVIEW
+            # This part of the script until EOF runs as the ec2-user user
+            sudo -u ec2-user -i <<EOF
 
-              # PARAMETERS
-              YOUR_USER_NAME="rjurney"
-              YOUR_EMAIL_ADDRESS="russell.jurney@gmail.com"
+            # OVERVIEW
+            # This part of the script sets username and email address in Git config
 
-              sudo -u ec2-user -i <<EOF
+            # PARAMETERS
+            YOUR_USER_NAME="rjurney"
+            YOUR_EMAIL_ADDRESS="russell.jurney@gmail.com"
 
-              git config --global user.name "$YOUR_USER_NAME"
-              git config --global user.email "$YOUR_EMAIL_ADDRESS"
+            git config --global user.name "$YOUR_USER_NAME"
+            git config --global user.email "$YOUR_EMAIL_ADDRESS"
 
-              # This part installs Python / Poetry
-              sudo -u ec2-user -i <<EOF
-              curl -sSL https://install.python-poetry.org | python3 -
+            # OVERVIEW
+            # This part of the script sets username and email address in Git config
 
-              EOF
+            # This part installs Python / Poetry
+            curl -sSL https://install.python-poetry.org | python3 -
+
+            echo 'export PATH="/home/ec2-user/.local/bin:$PATH"' >> /home/ec2-user/.bashrc
+
+            # Create a conda environment
+            conda create -n netography python=3.10 -y
+
+            # Install kernel with Jupyter
+            python -m ipykernel install --user --name=netography
+
+            EOF
 
   ExecutionRole:
     Type: "AWS::IAM::Role"
